spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

spring.main.allow-bean-definition-overriding=true

DB_USERNAME=postgres
DB_PASSWORD=0428Dullahan
JWT_SECRET=CXqzuivJR7yCWZ93BCHWUdyRI2JQWgSJWmpJicmK6jssvE5zyDg6FQx1dTQSfQxc
MAIL_USERNAME=davidochoa8510@gmail.com
MAIL_PASSWORD=libsujpyhdetfoob



